[functions.gerenciar-usuarios]
enabled = true
verify_jwt = true
import_map = "./functions/gerenciar-usuarios/deno.json"
entrypoint = "./functions/gerenciar-usuarios/index.ts"

[functions.registrar-historico]
enabled = true
verify_jwt = true
import_map = "./functions/registrar-historico/deno.json"
entrypoint = "./functions/registrar-historico/index.ts"